name: checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
    - uses: swift-actions/setup-swift@v1
      with: 
        swift-version: '5.9.2'

    - run: swift --version

    - name: build
      run: make build

    - name: test
      run: make test
