name: release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - name: exit if not on main branch
      if: endsWith(github.ref, 'main') == false
      run: exit -1
      
    - uses: actions/checkout@v3
    - uses: jdx/mise-action@v2

    - name: install tools
      run: make tools

    - name: create artifact
      run: make archive
    
    - name: create release
      uses: ncipollo/release-action@v1
      with:
        artifactErrorsFailBuild: true
        artifacts: "tuist-plugin-outdated.tuist-plugin.zip"
        draft: true
        skipIfReleaseExists: true
